.PHONY: help test test-autogenerated test-scenarios test-all lint install-devcontainer-cli

FEATURES := pyspelling cspell
BASE_IMAGES := debian:latest ubuntu:latest mcr.microsoft.com/devcontainers/base:ubuntu

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

install-devcontainer-cli: ## Install the devcontainer CLI
	npm install -g @devcontainers/cli

test: test-autogenerated test-scenarios ## Run all tests (autogenerated + scenarios)

test-autogenerated: ## Run autogenerated tests for all features against all base images
	@for feature in $(FEATURES); do \
		for image in $(BASE_IMAGES); do \
			echo "\n========================================"; \
			echo "Testing '$$feature' against '$$image'"; \
			echo "========================================\n"; \
			devcontainer features test --skip-scenarios -f $$feature -i $$image . ; \
		done; \
	done

test-scenarios: ## Run scenario tests for all features
	@for feature in $(FEATURES); do \
		echo "\n========================================"; \
		echo "Testing '$$feature' scenarios"; \
		echo "========================================\n"; \
		devcontainer features test -f $$feature --skip-autogenerated --skip-duplicated . ; \
	done

test-pyspelling: ## Run all tests for the pyspelling feature
	@for image in $(BASE_IMAGES); do \
		echo "\n========================================"; \
		echo "Testing 'pyspelling' against '$$image'"; \
		echo "========================================\n"; \
		devcontainer features test --skip-scenarios -f pyspelling -i $$image . ; \
	done
	devcontainer features test -f pyspelling --skip-autogenerated --skip-duplicated .

test-pyspelling-quick: ## Run pyspelling autogenerated test against a single base image
	devcontainer features test --skip-scenarios -f pyspelling -i mcr.microsoft.com/devcontainers/base:ubuntu .

test-cspell: ## Run all tests for the cspell feature
	@for image in $(BASE_IMAGES); do \
		echo "\n========================================"; \
		echo "Testing 'cspell' against '$$image'"; \
		echo "========================================\n"; \
		devcontainer features test --skip-scenarios -f cspell -i $$image . ; \
	done
	devcontainer features test -f cspell --skip-autogenerated --skip-duplicated .

test-cspell-quick: ## Run cspell autogenerated test against a single base image
	devcontainer features test --skip-scenarios -f cspell -i mcr.microsoft.com/devcontainers/base:ubuntu .

lint: ## Lint install scripts with shellcheck
	@echo "Linting install scripts..."
	@for feature in $(FEATURES); do \
		echo "  src/$$feature/install.sh"; \
		shellcheck src/$$feature/install.sh; \
	done
	@echo "Linting test scripts..."
	@find test -name '*.sh' -print -exec shellcheck -x -e SC1091 {} \;
	@echo "Lint passed."
